nodeLinker: node-modules
pnpMode: "loose"

npmScopes:
  apptractive:
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
