name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: lint and test
        run: npx nx run-many --target=format:check,lint,test,build --projects=react-app --parallel=3

      - name: Run codegen script
        run: yarn codegen

      - name: Run output script
        run: yarn output
